<?php
// $Id$

/**
 * Implement hook_theme().
 */
function elementstng_theme() {
  $file = array(
    'file' => 'elementstng.theme.inc',
    'path' => drupal_get_path('module', 'elementstng') . '/includes',
  );
  $element_names = array(
    'markup',
    'page',
    'html_tag',
    'container',
  );
  foreach ($element_names as $element_name) {
    $theme["elementstng_$element_name"] = $file + array(
      'variables' => array(
        'element' => NULL,
      ),
    );
  }

  return $theme;
}

/**
 * Initialize the element API.
 */
function elementstng() {
  module_load_include('inc', 'elementstng', '/includes/elementstng.elements');
}

/**
 * Get new or overriden properties for elements.
 *
 * @param $type string
 *   The machine-readable name of the element to get properties for.
 *
 * @return array
 *   Keys and values are property names and values.
 */
function elementstng_element_properties($type) {
  static $info = NULL;

  if (is_null($info)) {
    $info = module_invoke_all('elementstng_element_properties');
  }

  return isset($info[$type]) ? $info[$type] : array();
}