<?php
// $Id$

/**
 * @file
 * Drupal's form handling API.
 *
 * @see fapitng_Form::build()
 * @see elementstng_Element::expand()
 * @see elementstng_Element::render()
 * @see fapitng_Form::receive()
 * @see fapitng_Form::validate()
 * @see fapitng_FormBase::submit()
 *
 * Form handling has the following stages:
 * CONSTRUCTION
 * - Prepare
 *   Fill a form with all the necessary default elements.
 * - Build
 *   This is where all information about the form is gathered. No form logic is
 *   being executed yet.
 * - Expand
 *   This is the first layer with form logic to expand the form's
 *   functionality, i.e. convert a password confirm element to two separate
 *   fields with extra validation.
 * USER INTERACTION
 * - Render (optional)
 *   Make a form ready for display on a screen. This stage is passed when
 *   submitting a form programmatically.
 *
 * At this point the form can be populated with data, either programmatically
 * or through the interface.
 *
 * - Populate (Optional)
 *   The form receives user input and prepares it for validation. This stage is
 *   passed when submitting a form programmatically.
 * - Validate (Optional)
 *   Check user input for a rendered form. This stage is passed when submitting
 *   a form programmatically.
 * PROCESSING
 * - Submit
 *   Process input after the form has been submitted. Data can be stored or
 *   actions taken.
 */

/**
 * Implement hook_theme().
 */
function fapitng_theme() {
  $file = array(
    'file' => 'fapitng.theme.inc',
    'path' => drupal_get_path('module', 'fapitng') . '/includes/',
  );
  $theme['fapitng_form'] = $file + array(
    'variables' => array(
      'element' => NULL,
    ),
  );
  $element_names = array(
    'label',
    'required_marker',
    'fieldset',
    'vertical_tabs',
    'textfield',
    'textarea',
    'tableselect',
    'button',
    'image_button',
    'select',
    'radio',
    'radios',
    'checkbox',
    'checkboxes',
    'file', 
    'hidden',
  );
  foreach ($element_names as $element_name) {
    $theme["fapitng_form_$element_name"] = $file + array(
      'variables' => array(
        'element' => NULL,
      ),
    );
  }

  return $theme;
}

/**
 * Get a Drupal form for display.
 *
 * @param $form_id string
 *   The identifier for this form. Does not necessarily equal the HTML ID.
 * @param $build_callbacks array
 *   The names of the form builder functions.
 * @param ...
 *   Additional arguments to pass on to the build callbacks.
 *
 * @return string
 */
function fapitng_form($form_id, array $build_callbacks) {
  $arguments = array_slice(func_get_args(), 2);

  $form = fapitng_form_construct($form_id, $build_callbacks, FALSE, $arguments);
  $form->populate();
  $output = $form->render();

  return $output;
}

/**
 * Construct a Drupal form.
 * 
 * @param $form_id string
 *   The identifier for this form. Does not necessarily equal the HTML ID.
 * @param $build_callbacks array
 *   The names of the form builder functions.
 * @param $programmed boolean
 *   Whether the form will be handled programmatically or through the user
 *   interface.
 * @param ...
 *   Additional arguments to pass on to the build callbacks.
 */
function fapitng_form_construct($form_id, array $build_callbacks = array(), $programmed = FALSE, array $arguments = array()) {
  // @todo Remove when moving to core.
  elementstng();
  module_load_include('inc', 'fapitng', '/includes/fapitng.elements');

  // Prepare a new form and form state.
  $form_state = new fapitng_FormState($arguments, $programmed);
  $form = new fapitng_Form($form_id, $build_callbacks, $form_state);

  $form->prepare();
  $form->build();
  $form->expand();

  return $form;
}

/**
 * Page callback to display a form.
 */
function fapitng_form_page($form_id, array $build_callbacks) {
  return array(
    '#markup' => fapitng_form($form_id, $build_callbacks),
  );
}

/**
 * Contains a form's behavior.
 */
class fapitng_FormState {
  public $arguments = array();
  public $cache = FALSE;
  public $programmed = FALSE;
  public $raw_input = array();
  public $rebuild = FALSE;
  public $redirect = '';
  public $submit_element = NULL;

  function __construct(array $arguments, $programmed = FALSE) {
    $this->arguments = $arguments;
    $this->programmed = $programmed;
  }
}