<?php
// $Id$

function fubar_init() {
  if (arg(0) != 'fubar') {
    drupal_set_message(l('Test FAPI TNG', 'fubar'));
  }
}

function fubar_menu() {
  $items['fubar'] = array(
    'page callback' => 'fubar',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function fubar() {
  $execution_fapitng = 0;
  $execution_fapi = 0;

  if (!is_numeric(arg(1))) {
    drupal_not_found();
  }
  $forms = arg(1) ? arg(1) : 1;
  $i = 0;
  while ($i < $forms) {
    $i++;

    $start = microtime(TRUE);
    $fapitng = fapitng_form('fubar_form_fapitng', array('fubar_form_fapitng'));
    $halftime = microtime(TRUE);
    $fapi = drupal_render(drupal_get_form('fubar_form_fapi'));
    $end = microtime(TRUE);

    $execution_fapitng += $halftime - $start;
    $execution_fapi += $end - $halftime;
  }
  $execution_fapitng = $execution_fapitng / $forms * 1000;
  $execution_fapi = $execution_fapi / $forms * 1000;

  drupal_set_message(t('Render !link1, !link1000 or !link10000 form(s).', array('!link1' => l('1', 'fubar/1'), '!link1000' => l('1000', 'fubar/1000'), '!link10000' => l('10,000', 'fubar/10000'))));
  drupal_set_message(t('Average execution time for FAPI TNG: !executionms.', array('!execution' => round($execution_fapitng, 3))));
  drupal_set_message(t('Average execution time for FAPI: !executionms.', array('!execution' => round($execution_fapi, 3))));
  drupal_set_message(t('FAPI TNG is on average !differencems faster than FAPI.', array('!difference' => round($execution_fapi - $execution_fapitng, 3))));

  return array(
    'header_fapitng' => array(
      '#markup' => '<h2>' . t('FAPI TNG') . '</h2>',
    ),
    'fapitng' => array(
      '#markup' => $fapitng,
    ),
    'header_fapi' => array(
      '#markup' => '<h2>' . t('FAPI') . '</h2>',
    ),
    'fapi' => array(
      '#markup' => $fapi,
    ),
  );
}

function fubar_form_fapitng(fapitng_Form $form) {
  $form->addChild(new fapitng_FormTextarea('title', array(
    'title' => t('Title'),
    'description' => t('Description'),
    'required' => TRUE,
  )));
  $form->addChild(new fapitng_FormButton('submit', array(
    'value' => t('Submit'),
    'required' => TRUE,
  )));
}

function fubar_form_fapi(array $form, array &$form_state) {
  $form['title'] = array(
    '#type' => 'textarea',
    '#title' => t('Title'),
    '#description' => t('Description'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}